files:
  - source: "/marko-docs/*.md"
    translation: "/%original_path%/%locale%/%original_file_name%"
  - source: "/MDN_Intl_NumberFormat_NumberFormat/*.md"
    translation: "/%original_path%/%locale%/%original_file_name%"