files:
  - source: "/astro-container-reference/*.mdx"
    translation: "/%original_path%/%file_name%-%locale%.%file_extension%"
  - source: "/debugging-till-dawn/*.md"
    translation: "/%original_path%/%file_name%-%locale%.%file_extension%"
  - source: "/wget-manual-1.25.0/*.html"
    translation: "/%original_path%/%file_name%-%locale%.%file_extension%"
